parameters:
  sonata.admin.options.select2: true

services:
  _defaults:
    autowire: true
    autoconfigure: true

  _instanceof:
    Sonata\AdminBundle\Admin\AdminExtensionInterface:
      tags: [ 'slcorp.admin.extension' ]
    Slcorp\AdminBundle\Application\Component\BaseAdmin:
      bind:
        $extensions: !tagged_iterator slcorp.admin.extension

  Slcorp\AdminBundle\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  Slcorp\AdminBundle\Application\Component\Form\DynamicEntityTypeExtension:
    tags: [ 'form.type_extension' ]

  sonata.admin.controller.crud:
    class: Slcorp\AdminBundle\Presentation\Controller\BaseCRUDController


  Slcorp\AdminBundle\Application\Component\Extensions\AdminControlExtension:
    tags: ['slcorp.admin.extension']

  Slcorp\AdminBundle\Application\Component\Extensions\UserSettingsExtension:
    tags: ['slcorp.admin.extension']